name: FaceApp
options:
  bundleIdPrefix: com.faceapp
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

settings:
  SWIFT_VERSION: "5.9"
  DEVELOPMENT_TEAM: ""

targets:
  FaceApp:
    type: application
    platform: iOS
    sources:
      - path: FaceApp
        excludes:
          - "**/.DS_Store"
    settings:
      INFOPLIST_FILE: FaceApp/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.faceapp.nightlife
      MARKETING_VERSION: "1.0.0"
      CURRENT_PROJECT_VERSION: "1"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      CODE_SIGN_STYLE: Automatic
      ENABLE_PREVIEWS: YES
      GENERATE_INFOPLIST_FILE: NO
      SWIFT_EMIT_LOC_STRINGS: YES
    entitlements:
      path: FaceApp/FaceApp.entitlements
      properties:
        keychain-access-groups: []

schemes:
  FaceApp:
    build:
      targets:
        FaceApp: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
